Resources:
  DynamoSchemaTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: !Ref DynamoTableName
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: feedId
          AttributeType: S
      KeySchema:
        - AttributeName: feedId
          KeyType: HASH
